### ISSUE TITLE
cli-extra  target needed with startcli

### ISSUE THREAD

**Issue by DennisLfromGA** [iptoux/kaliton#1]
When I try to launch the headless target with [`startcli`](https://github.com/dnschneid/crouton/blob/master/targets/cli-extra) the below error is thrown:

```
sudo startcli -n kaliton
/mnt/stateful_partition/crouton/chroots/kaliton does not contain target 'cli-extra'
```

-**DennisLfromGA**

**Comment by iptoux** [comment]
Thanks for reporting, i will look and see if i found the bug. 

You should still enter with `sudo enter-chroot -n kaliton` as workaraound.

**Comment by DennisLfromGA** [comment]
@iptoux,

Yup, that's what I've done.

-**DennisLfromGA**

**Comment by DennisLfromGA** [comment]
@iptoux,

After adding the cli-extra target `startcli` worked fine. 👍

-**DennisLfromGA**

**Comment by iptoux** [comment]
> @iptoux,
> 
> After adding the cli-extra target `startcli` worked fine - for me. 👍
> 
> -**DennisLfromGA**

Use this please only as workearound, the error is in host-bin/startcli it, it calls the extra-cli target in chroot, i changed this (local) to default and created an startless for the headless mode. Do testruns now and will push soon :)
